class Constants:
    SYMBOL = 'symbol'
    INTVAL = 'integerConstant'
    STRINGVAL = 'stringval'
    KEYWORD = 'keyword'
    IDENTIFIER = 'identifier'

    CLASS = 'class'
    CLASSVARDEC = 'classVarDec'
    SUBROUTINEDEC = 'subroutineDec'
    PARAMETER_LIST = 'parameterList'
    SUBROUTINEBODY = 'subroutineBody'
    VARDEC = 'varDec'
    STATEMENTS = 'statements'
    SUBROUTINECALL = 'subroutineCall'
    EXPRESSION = 'expression'
    EXPRESSION_LIST = 'expressionList'
    TERM = 'term'

    STATIC = 'static'
    FIELD = 'field'
    CONSTRUCTOR = 'constructor'
    FUNCTION = 'function'
    METHOD = 'method'
    VOID = 'void'
    VAR = 'var'

    INT = 'int'
    CHAR = 'char'
    BOOlEAN = 'boolean'

    IF = 'if'
    LET = 'let'
    DO = 'do'
    WHILE = 'while'
    RETURN = 'return'
    ELSE = 'else'

    IF_STATEMENT = 'ifStatement'
    LET_STATEMENT = 'letStatement'
    DO_STATEMENT = 'doStatement'
    WHILE_STATEMENT = 'whileStatement'
    RETURN_STATEMENT = 'returnStatement'

    TRUE = 'true'
    FALSE = 'false'
    NULL = 'null'
    THIS = 'this'
